#!/bin/sh

# Get the latest version of chrome
version="$1"
if [ -z "$version" ]; then
    version=$(google-chrome --version | cut -d ' ' -f 3)
fi
echo version=$version

api="https://googlechromelabs.github.io/chrome-for-testing/known-good-versions-with-downloads.json"

# Get the url of corresponding chromedriver
url=$(
    curl -s "$api" |
    jq -r ".versions[] | select(.version==\"$version\").downloads.chromedriver[] | select(.platform==\"linux64\").url"
)
echo url=$url

if [ -z "$url" ]; then
    echo "Could not find url for downloadable chromedriver"
    exit 1
fi

if [ -n "$1" ]; then
    echo "Found downloadable chromedriver $version"
    exit 0
fi

# Download chromedriver
curl -sL -o /tmp/chromedriver.zip "$url"

if [ ! -f /tmp/chromedriver.zip ]; then
    echo "Could not download chromedriver"
    exit 1
fi

# Extract chromedriver
unzip -d /tmp -o -j /tmp/chromedriver.zip "*/chromedriver"
rm /tmp/chromedriver.zip
ls -lh /tmp/chromedriver

if [ ! -f /tmp/chromedriver ]; then
    echo "Could not extract chromedriver binary"
    exit 1
fi

# Move chromesriver over previous version
target=`which chromedriver`
if [ -z "$target" ]; then
    echo "Could not find CURRENT chromedriver binary"
    echo "New version is available at /tmp/chromedriver"
    exit 1
fi

mv -vf /tmp/chromedriver "$target"
