# .github/workflows/test.yml
name: Script Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install python
      uses: actions/setup-python@v5
      with:
          python-version: 3.11
    - run: pip install pytest
    - run: pytest -v tests
